### ISSUE TITLE
Website bug/issue

### ISSUE THREAD

**Issue by vpiskunov** [hello-aurora/.github#1]
Hey @jeremybarbet, @hello-aurora looks really good! One issue I've just noticed was, hello-aurora.com had spun up my M2 Max CPU & fans all the way to intel temperatures, so just wanted to give you a heads up (clearly wrong repo & place, but not sure where to reach you at). 

<img width="1175" alt="Screenshot 2024-08-07 at 00 40 48" src="https://github.com/user-attachments/assets/39ea2d60-a117-42fb-9ad5-d8fe910f2a80">

Feel free to reach out on vlad at primeboard-dot-org if anything, happy to help debug this with any performance profiling / flame charts etc.

**Comment by jeremybarbet** [comment]
Hey @vpiskunov, thanks for the nice word!

That's a good catch. That's the downside of having a computer where the fans don't go off when that happens. I didn't really think of checking the CPU. Anyway, I can reproduce it in dev and production, will take a look at it asap. I will let you know.

Thanks!

**Comment by jeremybarbet** [comment]
Should be fixed now. Feel free to re-open if you still see an issue!
